//
//  FavoriteModels.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 27/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favorite {
  // MARK: Use cases
  
  enum FavoriteList {
    struct Request {
        init (withPredicate predicate: PhoneStore.Predicate = PhoneStore().getSortPredicate()?.predicate ?? .priceAscending) {
            self.loadPridicate = predicate
        }
        let loadPridicate: PhoneStore.Predicate
    }

    struct Response {
        var favoritePhoneList: [Phone]?
    }

    struct ViewModel {
        struct DisplayPhone: Equatable {
            let id: Int
            let name: String
            let description: String
            let price: String
            let rating: String
            let thumbnailPath: String
        }
        var displayPhone: [DisplayPhone]
    }
  }
}
