//
//  FavoritePresenter.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 27/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritePresentationLogic: BasePresenterLogic {
    func presentSomething(response: Favorite.FavoriteList.Response)
}

class FavoritePresenter: BasePresenter, FavoritePresentationLogic {
    weak var viewController: FavoriteDisplayLogic? {
        didSet{
            baseViewController = viewController
        }
    }
    // MARK: Do something

    func presentSomething(response: Favorite.FavoriteList.Response) {
        let viewModel = Favorite.FavoriteList.ViewModel()
        viewController?.displayFavoriteList(viewModel: viewModel)
    }
}
