//
//  FavoriteViewController.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 27/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteDisplayLogic: BaseDisplayLogic {
    func displayFavoriteList(viewModel: Favorite.FavoriteList.ViewModel)
}

class FavoriteViewController: BaseViewController, FavoriteDisplayLogic {
    var interactor: FavoriteBusinessLogic?
    var router: (NSObjectProtocol & FavoriteRoutingLogic & FavoriteDataPassing)?
    var favoritePhoneList: [Favorite.FavoriteList.ViewModel.DisplayPhone] = []

    // MARK: - View elements
    lazy var favoriteTableView: UITableView = {
        let favoriteTableView = UITableView() <-< {
            $0.register(ListTableViewCell.self)
            $0.tableHeaderView = UIView(frame: .zero)
            $0.tableFooterView = UIView(frame: .zero)
            $0.backgroundColor = .clear
            $0.alwaysBounceVertical = true
            $0.estimatedRowHeight = 120.0
            $0.rowHeight = UITableView.automaticDimension
            $0.separatorStyle = .singleLine
            $0.separatorInset = .zero
            $0.delegate = self
            $0.dataSource = self
        }
        return favoriteTableView
    }()

    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = FavoriteInteractor()
        let presenter = FavoritePresenter()
        let router = FavoriteRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setUI()
        loadFavoriteList()
    }

    // MARK: - View Setup
    func setUI() {
        view.addSubview(favoriteTableView, attachedTo: view)
    }

    // MARK: Do something
    func loadFavoriteList() {
        let request = Favorite.FavoriteList.Request()
        interactor?.fetchFavoriteList(request: request)
    }

    func displayFavoriteList(viewModel: Favorite.FavoriteList.ViewModel) {
        favoritePhoneList = viewModel.displayPhone
        favoriteTableView.reloadData()
    }
}

extension FavoriteViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return favoritePhoneList.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = dequeueReuseableListTableViewCell(for: indexPath),
        let favoritePhoneData = favoritePhoneList[safe: indexPath.row] else { return UITableViewCell() }
        cell.configure(with: favoritePhoneData)
//        cell.delegate = self
        return cell
    }
}

extension FavoriteViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        return true
    }

    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if (editingStyle == .delete) {
            if let id = favoritePhoneList[safe: indexPath.row]?.id {
                interactor?.removeFavoritePhone(withId: id)
            }
        }
    }
}

// MARK: - ListTableViewCell Factory Method
extension FavoriteViewController {
    func dequeueReuseableListTableViewCell(for indexPath: IndexPath) -> ListTableViewCell? {
        return self.favoriteTableView.dequeueReusableCell(for: ListTableViewCell.self, for: indexPath)
    }
}

