//
//  FavoriteWorker.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 27/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Realm
import RealmSwift

class FavoriteWorker {
    let phoneStore = PhoneStore.shared

    func loadFavoritePhoneList(withPredicate predicate: PhoneStore.Predicate = .priceAscending) -> [Phone]? {
        return phoneStore.getFavoritePhoneList(predicate)
    }

    func getObervePhoneList() -> Results<Phone>? {
        return DataManager.shared.objects(Phone.self)
    }

    @discardableResult
    func setFavorite(withId id: Int) -> [Phone]? {
        phoneStore.setFavorite(withId: id)
        return phoneStore.getFavoritePhoneList()
    }

    func getOberveSort() -> Results<SortPredicate>? {
        return DataManager.shared.objects(SortPredicate.self)
    }
}
