//
//  FavoriteRouter.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 27/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteRoutingLogic {
    func navigateToDetail()
}

protocol FavoriteDataPassing {
    var dataStore: FavoriteDataStore? { get }
}

class FavoriteRouter: NSObject, FavoriteRoutingLogic, FavoriteDataPassing {
    weak var viewController: FavoriteViewController?
    var dataStore: FavoriteDataStore?

    // MARK: Routing


    // MARK: Navigation
    func navigateToDetail() {
        let destinationVC = DetailViewController()
        var destinationDS = destinationVC.router?.dataStore
        passDataToDetailVC(source: dataStore!, destination: &destinationDS!)
        viewController?.show(destinationVC, sender: nil)
    }

    // MARK: Passing data
    func passDataToDetailVC(source: FavoriteDataStore, destination: inout DetailDataStore) {
        if let selectedRow = viewController?.favoriteTableView.indexPathForSelectedRow?.row {
            destination.phoneId = source.favoritePhoneList[selectedRow].id
        }
    }

}
