//
//  FavoriteInteractor.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 27/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteBusinessLogic {
  func fetchFavoriteList(request: Favorite.FavoriteList.Request)
}

protocol FavoriteDataStore {
  //var name: String { get set }
}

class FavoriteInteractor: FavoriteBusinessLogic, FavoriteDataStore {
  var presenter: FavoritePresentationLogic?
  var worker: FavoriteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchFavoriteList(request: Favorite.FavoriteList.Request) {
    worker = FavoriteWorker()
    worker?.doSomeWork()
    
    let response = Favorite.FavoriteList.Response()
    presenter?.presentSomething(response: response)
  }
}
