//
//  ListModels.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 26/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List {
  // MARK: Use cases
  
  enum DeviceList {
    struct Request {
        let fetchPridicate: PhoneStore.Predicate
    }

    struct Response {
        var phoneList: [Phone]?
        var errorMessage: String?
    }

    struct Error {
        let errorMessage: String
    }

    struct ViewModel {
        struct DisplayPhone {
            let id: Int
            let name: String
            let description: String
            let price: String
            let rating: String
            let thumbnailPath: String
            let isFavorite: Bool
        }
        var displayPhone: [DisplayPhone]
    }
  }
}
