//
//  ListWorker.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 26/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker {
  func fetchPhoneList(completion: @escaping (Result<[Phone]>) -> Void) {
    Network.shared.request(router: Router.getMobilesList) { (result: Result<[Phone]>) in
        completion(result)
    }
  }
}
