//
//  ListPresenter.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 26/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic: BasePresenterLogic {
    func presentPhoneList(response: List.DeviceList.Response)
}

class ListPresenter: BasePresenter, ListPresentationLogic {
    weak var viewController: ListDisplayLogic? {
        didSet{
            baseViewController = viewController
        }
    }

    // MARK: Present to ViewController
    func presentPhoneList(response: List.DeviceList.Response) {
        defer { hideLoading() }
        var viewModel = List.DeviceList.ViewModel(displayPhone: [])
        if let phoneList = response.phoneList {
            phoneList.forEach {
                let phoneModel = List.DeviceList.ViewModel.DisplayPhone(id: $0.id,
                                                                        name: $0.name,
                                                                        description: $0._description,
                    price: "Price: $\(String(format: "%.2f", $0.price))",
                    rating: "Rating: \($0.rating)",
                    thumbnailPath: $0.thumbImageURL,
                    isFavorite: $0.isFavorite)
                viewModel.displayPhone.append(phoneModel)
            }
            viewController?.displayDeviceList(viewModel: viewModel)
        } else if let errorMessage = response.errorMessage {
            let error = List.DeviceList.Error(errorMessage: errorMessage)
            viewController?.displayError(error: error)
        }
    }
}
