//
//  ListRouter.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 26/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListRoutingLogic {
    func navigateToDetail()
}

protocol ListDataPassing {
    var dataStore: ListDataStore? { get }
}

class ListRouter: NSObject, ListRoutingLogic, ListDataPassing {
    weak var viewController: ListViewController?
    var dataStore: ListDataStore?

    // MARK: Routing

    // MARK: Navigation
    func navigateToDetail() {
        let destinationVC = DetailViewController()
        var destinationDS = destinationVC.router?.dataStore
        passDataToDetailVC(source: dataStore!, destination: &destinationDS!)
        viewController?.show(destinationVC, sender: nil)
    }

    // MARK: Passing data
    func passDataToDetailVC(source: ListDataStore, destination: inout DetailDataStore) {
        if let selectedRow = viewController?.listTableView.indexPathForSelectedRow?.row {
            destination.phoneId = source.phoneList[selectedRow].id
        }
    }
}
