//
//  FavoriteWorkerTests.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 28/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Mobile_Phone_Buyer_s_Guide
import XCTest

class FavoriteWorkerTests: XCTestCase {
    // MARK: Subject under test
    var favoritePhoneData: [Phone]!
    var notFavoritePhoneData: [Phone]!
    var sortData: SortPredicate!
    var sut: FavoriteWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupFavoriteWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupFavoriteWorker() {
        sut = FavoriteWorker()
        favoritePhoneData = [Phone(id: 0,
                                   name: "MockName",
                                   price: 100.222,
                                   brand: "MockBrand",
                                   desciption: "MockDescription",
                                   rating: 4.5,
                                   thumbImageURL: "link",
                                   isFavorite: true)]
        notFavoritePhoneData = [Phone(id: 1,
                                      name: "MockName",
                                      price: 100.222,
                                      brand: "MockBrand",
                                      desciption: "MockDescription",
                                      rating: 4.5,
                                      thumbImageURL: "link",
                                      isFavorite: false)]
        sortData = SortPredicate(predicate: .ratingDescending)

    }

    // MARK: Test doubles

    // MARK: Tests
    func testLoadFavoritePhoneList() {
        // Given
        DataManager.shared.add(favoritePhoneData)
        DataManager.shared.add(notFavoritePhoneData)

        // When
        let loadedFavoritePhoneList = sut.loadFavoritePhoneList()

        // Then
        XCTAssertEqual(favoritePhoneData, loadedFavoritePhoneList)
    }

    func testRemoveFavorite() {
        // Given
        DataManager.shared.add(favoritePhoneData)

        // When
        sut.setFavorite(withId: (favoritePhoneData.first?.id)!)
        let loadedPhoneList = sut.loadFavoritePhoneList()

        // Then
        XCTAssertEqual(loadedPhoneList, [])
    }

    func testGetObervePhoneList() {
        // Given
        DataManager.shared.add(favoritePhoneData)

        // When
        let observerList = sut.getObervePhoneList()

        // Then
        XCTAssertNotNil(observerList)
    }

    func testGetOberveSort() {
        // Given
        DataManager.shared.add(sortData)

        // When
        let observerList = sut.getOberveSort()

        // Then
        XCTAssertNotNil(observerList)
    }

}
