////
////  DetailWorkerTests.swift
////  Mobile Phone Buyer’s Guide
////
////  Created by Tanasak Ngerniam on 28/1/2562 BE.
////  Copyright (c) 2562 NilNilNil. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import Mobile_Phone_Buyer_s_Guide
//import XCTest
//
//class DetailWorkerTests: XCTestCase {
//  // MARK: Subject under test
//  
//  var sut: DetailWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp() {
//    super.setUp()
//    setupDetailWorker()
//  }
//  
//  override func tearDown() {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupDetailWorker() {
//    sut = DetailWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething() {
//    // Given
//    
//    // When
//    
//    // Then
//  }
//}
