//
//  DetailInteractor.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 28/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func doSomething(request: Detail.Something.Request)
}

protocol DetailDataStore {
    var phoneId: Int! { get set }
    var phoneDetail: Phone? { get }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker = DetailWorker()
    var phoneId: Int!
    var phoneDetail: Phone?


    // MARK: Do something
    func doSomething(request: Detail.Something.Request) {
        if let phoneData = worker.getPhoneDetail(withId: phoneId) {
            let response = Detail.Something.Response(phoneDetail: phoneData, phoneImages: [])
            phoneDetail = phoneData
            presenter?.presentSomething(response: response)
            fetchPhoneImages()
        }
    }

    func fetchPhoneImages() {
        worker.fetchPhoneImages(withId: phoneId) { [weak self] (result) in
            switch result {
            case .success(let value):
                let response = Detail.Something.Response.init(phoneDetail: self?.phoneDetail, phoneImages: value)
                self?.presenter?.presentSomething(response: response)
            case .failure(let error):
                break
            }
        }
    }
}
