//
//  DetailPresenter.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 28/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentSomething(response: Detail.Something.Response)
    
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Detail.Something.Response) {
        if let phoneDetail = response.phoneDetail {
            let viewModel = Detail.Something.ViewModel.init(id: phoneDetail.id,
                                                            name: phoneDetail.name,
                                                            description: phoneDetail._description,
                                                            price: "Price: $\(String(format: "%.2f", phoneDetail.price))",
                rating: "Rating: \(phoneDetail.rating)",
                imagesPath: response.phoneImages.map {
                    if !$0.url.contains("http") {
                        return "http://" + $0.url
                    }
                    return $0.url
            })
            viewController?.displaySomething(viewModel: viewModel)
        }
    }
}
