//
//  DetailWorker.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 28/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    let phoneStore = PhoneStore()

    func getPhoneDetail(withId id: Int) -> Phone? {
        return phoneStore.getPhoneDetail(withId: id)
    }

    func fetchPhoneImages(withId id: Int, completion: @escaping (Result<[PhoneImage]>) -> Void) {
        Network.shared.request(router: Router.getMobileImages(mobileId: "\(id)")) { (result: Result<[PhoneImage]>) in
            completion(result)
        }
    }
}
