//
//  DetailModels.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 28/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases

    enum PhoneDetail {
        struct Request {}

        struct Response {
            var phoneDetail: Phone?
            var phoneImages: [PhoneImage] = []
            var errorMessage: String?
        }

        struct Error {
            let errorMessage: String
        }
        
        struct ViewModel: Equatable {
            let id: Int
            let name: String
            let description: String
            let price: String
            let rating: String
            let imagesPath: [String]
        }
    }
}
