//
//  DetailRouter.swift
//  Mobile Phone Buyer’s Guide
//
//  Created by Tanasak Ngerniam on 28/1/2562 BE.
//  Copyright (c) 2562 NilNilNil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic {
}

protocol DetailDataPassing {
  var dataStore: DetailDataStore? { get }
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing {
  weak var viewController: DetailViewController?
  var dataStore: DetailDataStore?
  
  // MARK: Routing

  // MARK: Navigation
  
  // MARK: Passing data
  
}
